### ISSUE TITLE
Any update for jVectorMap for Kibana 6.1.1?

### ISSUE THREAD

**Issue by neilc2016** [snuids/Elastic-5.0-Offline-Map-Visualizer#4]

**Comment by snuids** [comment]
Hi, I will probably not work on this anymore. Every version of Elastic Search breaks the compatibility with the plugins which is painful. I will probably still work on the traffic light plugin for ELK 6.0 but for the maps, I don't have any use of them anymore for the moment.
Basically, the code is probably fine but most of the imports must be changed with each new version which can be a a difficult job as it is difficult to find a good plugin documentation from Elastic.
Sorry for that,
Cheers, Arnaud
